id: ServiceNow_CMDB_Test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: ServiceNow_CMDB_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0f2d412d-b518-400f-8894-3cb24626aad8
    type: start
    task:
      id: 0f2d412d-b518-400f-8894-3cb24626aad8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 2b9b7bf8-41ea-45d2-8dae-54e99fcb6e7e
    type: regular
    task:
      id: 2b9b7bf8-41ea-45d2-8dae-54e99fcb6e7e
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 61b746fe-d1c0-4bab-8203-0111bb718eab
    type: regular
    task:
      id: 61b746fe-d1c0-4bab-8203-0111bb718eab
      version: -1
      name: servicenow-cmdb-records-list
      script: '|||servicenow-cmdb-records-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      class:
        simple: cmdb_ci_linux_server
      limit:
        simple: "1"
      offset: {}
      query: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: f7ad19d8-014b-4abd-8896-c1f2cc09839a
    type: regular
    task:
      id: f7ad19d8-014b-4abd-8896-c1f2cc09839a
      version: -1
      name: servicenow-cmdb-record-get-by-id
      script: '|||servicenow-cmdb-record-get-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      class:
        simple: ${ServiceNowCMDB.Record.Class}
      fields: {}
      relation_limit: {}
      relation_offset: {}
      sys_id:
        simple: ${ServiceNowCMDB.Record.SysID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: ae6fa0f7-db42-4762-8edd-a4ed94f9f697
    type: regular
    task:
      id: ae6fa0f7-db42-4762-8edd-a4ed94f9f697
      version: -1
      name: servicenow-cmdb-record-create
      script: '|||servicenow-cmdb-record-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      attributes:
        simple: name=Test Playbook Record
      class:
        simple: cmdb_ci_linux_server
      fields: {}
      inbound_relations: {}
      outbound_relations: {}
      relation_limit: {}
      relation_offset: {}
      source: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: a4d93ba6-630c-4f26-836f-2db310046d29
    type: condition
    task:
      id: a4d93ba6-630c-4f26-836f-2db310046d29
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ServiceNowCMDB.Record.Attributes.name
            iscontext: true
          right:
            value:
              simple: Test Playbook Record
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 665873c8-962f-43a6-83a3-a9bd0f4b9a04
    type: regular
    task:
      id: 665873c8-962f-43a6-83a3-a9bd0f4b9a04
      version: -1
      name: servicenow-cmdb-record-update
      script: '|||servicenow-cmdb-record-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      attributes:
        simple: name=Updated Name Test Playbook
      class:
        simple: ${ServiceNowCMDB.Record.Class}
      fields: {}
      relation_limit: {}
      relation_offset: {}
      source: {}
      sys_id:
        simple: ${ServiceNowCMDB.Record.SysID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 647989b4-6c7c-476b-88b9-8919fd5d7279
    type: regular
    task:
      id: 647989b4-6c7c-476b-88b9-8919fd5d7279
      version: -1
      name: servicenow-cmdb-record-add-relations
      script: '|||servicenow-cmdb-record-add-relations'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      class:
        simple: ${ServiceNowCMDB.Record.Class}
      fields: {}
      inbound_relations:
        simple: '[{''type'': ''cb5592603751200032ff8c00dfbe5d17'',''target'':''829e953a0ad3370200af63483498b1ea'',''sys_class_name'':''cmdb_ci_appl''}]'
      outbound_relations: {}
      relation_limit: {}
      relation_offset: {}
      source: {}
      sys_id:
        simple: ${ServiceNowCMDB.Record.SysID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: fcd63099-b369-4482-82f3-6f11e56e0d06
    type: condition
    task:
      id: fcd63099-b369-4482-82f3-6f11e56e0d06
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ServiceNowCMDB.Record.InboundRelations
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: b8a36a01-517e-426a-8476-c33eb77b946a
    type: regular
    task:
      id: b8a36a01-517e-426a-8476-c33eb77b946a
      version: -1
      name: servicenow-cmdb-record-delete-relations
      script: '|||servicenow-cmdb-record-delete-relations'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      class:
        simple: ${ServiceNowCMDB.Record.Class}
      fields: {}
      relation_limit: {}
      relation_offset: {}
      relation_sys_id:
        simple: ${ServiceNowCMDB.Record.InboundRelations.[0].sys_id}
      sys_id:
        simple: ${ServiceNowCMDB.Record.SysID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 69347674-0e81-44a2-8452-f7da24e14c5f
    type: condition
    task:
      id: 69347674-0e81-44a2-8452-f7da24e14c5f
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: ServiceNowCMDB.Record.InboundRelations
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 45e07e23-9a5c-4818-82d3-2c782cb01ff1
    type: title
    task:
      id: 45e07e23-9a5c-4818-82d3-2c782cb01ff1
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 869ac293-62ac-4de3-8ed4-b8a0a354187b
    type: condition
    task:
      id: 869ac293-62ac-4de3-8ed4-b8a0a354187b
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ServiceNowCMDB.Record.Attributes.name
            iscontext: true
          right:
            value:
              simple: Updated Name Test Playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 32497476-3018-4e14-84ee-4bab2dbbaef7
    type: condition
    task:
      id: 32497476-3018-4e14-84ee-4bab2dbbaef7
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ServiceNowCMDB.Record.Attributes.name
            iscontext: true
          right:
            value:
              simple: Updated Name Test Playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
