description: |-
  Run on a QRadar offense to get more information:

  * Get all correlations relevant to the offense
  * Get all logs relevant to the correlations (not done by default - set "GetCorrelationLogs" to "True")

  Inputs:
  * GetCorrelationLogs (default: False)
  * MaxLogsCount (default: 20)
id: QRadar - Get offense correlations v2
inputs:
- description: When set to "True", retrieves all of the offense's correlations logs
  key: GetCorrelationLogs
  playbookInputQuery:
  required: false
  value:
    simple: "True"
- description: 'Maximum number of log entires to query from QRadar (default: 20)'
  key: MaxLogsCount
  playbookInputQuery:
  required: false
  value:
    simple: "20"
- description: 'The QRadar offense ID '
  key: ID
  playbookInputQuery:
  required: true
  value:
    complex:
      accessor: labels.id
      root: incident
- description: The QRadar offense start time
  key: StartTime
  playbookInputQuery:
  required: true
  value:
    complex:
      accessor: labels.start_time
      root: incident
- description: |-
    If value "OnlyCRE" get only events made by CRE.
    Values can be "OnlyCRE", "OnlyNotCRE", "All".
  key: GetOnlyCREEvents
  playbookInputQuery:
  required: false
  value:
    simple: All
- description: 'Maximum number of correlations to query from QRadar (default: 100)'
  key: MaxCorrelationCount
  playbookInputQuery:
  required: false
  value:
    simple: "100"
- description: A comma-separated list of extra fields to get from each event.
  key: Fields
  playbookInputQuery:
  required: false
  value: {}
name: QRadar - Get offense correlations v2
outputs:
- contextPath: QRadar.Correlation.StartTime
  description: The correlation start time
- contextPath: QRadar.Correlation.CategoryID
  description: 'The correlation category id '
- contextPath: QRadar.Correlation.QID
  description: The correlation QID identifier
- contextPath: QRadar.Correlation.CREName
  description: The correlation name
- contextPath: QRadar.Correlation.CREDescription
  description: The correlation description
- contextPath: QRadar.Correlation
  description: The QRadar offense correlations
- contextPath: QRadar.Correlation.SourceIP
  description: The correlation source IP
- contextPath: QRadar.Correlation.DestinationIP
  description: The correlation destination IP
- contextPath: QRadar.Correlation.Category
  description: The correlation high level category
- contextPath: QRadar.Correlation.Username
  description: The correlation username
- contextPath: QRadar.Log
  description: The QRadar offense correlation logs
- contextPath: QRadar.Log.QID
  description: The log's correlation ID
- contextPath: QRadar.Log.SourceIP
  description: The log's source IP
- contextPath: QRadar.Log.DestinationPort
  description: The log's destination port
- contextPath: QRadar.Log.SourcePort
  description: The log's source port
- contextPath: QRadar.Log.DestinationIP
  description: The log's destination IP
- contextPath: QRadar.Log.Category
  description: The log's category
- contextPath: QRadar.Log.IdentityIP
  description: The log's identity IP
- contextPath: QRadar.Log.Username
  description: The log's username
- contextPath: QRadar.Log.StartTime
  description: The log's start time
- contextPath: QRadar.Log.Magnitude
  description: The log's magnitude
- contextPath: QRadar.Log.ProtocolName
  description: The log's protocol name
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "25"
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: db9fb0e9-591e-47b6-89e6-58e12e0a4b87
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: db9fb0e9-591e-47b6-89e6-58e12e0a4b87
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 7.5,
          "y": -440
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.GetOnlyCREEvents
          operator: inList
          right:
            value:
              simple: OnlyCRE,OnlyNotCRE, All
      label: "true"
    id: "1"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "true":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: 5fa964a0-5f5e-49eb-8a3d-bce2813adaf6
      iscommand: false
      name: Is CRE inserted correctly?
      type: condition
      version: -1
    taskid: 5fa964a0-5f5e-49eb-8a3d-bce2813adaf6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -372.5,
          "y": 140
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9adcf948-d938-4fc1-8da2-ec3d45741b5a
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 9adcf948-d938-4fc1-8da2-ec3d45741b5a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -160,
          "y": 1810
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 24b8da32-7dac-49c3-8114-138c7de88afb
      iscommand: false
      name: Get offense information
      type: title
      version: -1
      description: ''
    taskid: 24b8da32-7dac-49c3-8114-138c7de88afb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 295,
          "y": 370
        }
      }
  "6":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.GetCorrelationLogs
          operator: isEqualString
          right:
            value:
              simple: "True"
      - - left:
            iscontext: true
            value:
              simple: ${QRadar.Correlation.QID}
          operator: isExists
      label: "true"
    id: "6"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "true":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: 9c2dff46-d226-4772-830d-23aa0f91373b
      iscommand: false
      name: Should query for the correlations' logs?
      type: condition
      version: -1
    taskid: 9c2dff46-d226-4772-830d-23aa0f91373b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1390
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      headers: {}
      interval:
        simple: "1"
      query_expression:
        simple: |-
          SELECT *,
          "CRE Name" AS "CREName",
          "CRE Description" AS "CREDescription",
          CATEGORYNAME(highlevelcategory) AS "Category"
          ${QRadar.AdditionalFields}
          FROM events WHERE "CRE NAME" IS NULL AND INOFFENSE(${inputs.ID})
          LIMIT ${inputs.MaxCorrelationCount}
          START '${Time}'
      range: {}
      timeout:
        simple: "600"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook runs a QRadar query and return its results to the
        context.
      id: f0274f21-b268-4541-8022-33c88ae6efe4
      iscommand: false
      name: QRadarFullSearch
      playbookId: QRadarFullSearch
      type: playbook
      version: -1
    taskid: f0274f21-b268-4541-8022-33c88ae6efe4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      capitalize:
        simple: "True"
      inplace:
        simple: "False"
      input:
        simple: ${QRadar.Search.Result.events}
      input_key:
        simple: ${QRadar.Search.Result}
      key:
        simple: ${QRadar.Search.Results}
      output_key:
        simple: QRadar.Correlation
      replace_dict:
        simple: '{"sourceip": "SourceIP", "qid":"QID", "destinationip": "DestinationIP",
          "category": "CategoryID", "starttime": "StartTime"}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: cdf5cb18-1412-480a-8fb4-da287c2fdd02
      iscommand: false
      name: Change Context
      script: ChangeContext
      type: regular
      version: -1
    taskid: cdf5cb18-1412-480a-8fb4-da287c2fdd02
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1215
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.GetOnlyCREEvents
          operator: inList
          right:
            value:
              simple: All,OnlyCRE
      label: "true"
    id: "11"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "10"
      "true":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: a886a3db-ef29-417f-8319-344f42e9bfe0
      iscommand: false
      name: is All or OnlyCRE
      type: condition
      version: -1
    taskid: a886a3db-ef29-417f-8319-344f42e9bfe0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 150,
          "y": 880
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.GetOnlyCREEvents
          operator: inList
          right:
            value:
              simple: All,OnlyNotCRE
      label: "true"
    id: "12"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "10"
      "true":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: 3e3d2932-bc72-4848-82cb-24fdb5927955
      iscommand: false
      name: is All or OnlyNotCRE
      type: condition
      version: -1
    taskid: 3e3d2932-bc72-4848-82cb-24fdb5927955
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 880
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      headers: {}
      interval:
        simple: "1"
      query_expression:
        simple: |-
          SELECT *,
          "CRE Name" AS "CREName",
          "CRE Description" AS "CREDescription",
          CATEGORYNAME(highlevelcategory) AS "Category"
          ${QRadar.AdditionalFields}
          FROM events WHERE "CRE NAME" IS NULL AND INOFFENSE(${inputs.ID})
          LIMIT ${inputs.MaxCorrelationCount}
          START '${Time}'
      range: {}
      timeout:
        simple: "600"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook runs a QRadar query and return its results to the
        context.
      id: 5d5b577a-8443-4502-8818-9dc43e14cf2b
      iscommand: false
      name: QRadarFullSearch
      playbookId: QRadarFullSearch
      type: playbook
      version: -1
    taskid: 5d5b577a-8443-4502-8818-9dc43e14cf2b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 640,
          "y": 1040
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      GetOnlyCREEvents:
        simple: ${inputs.GetOnlyCREEvents}
      MaxLogsCount:
        simple: "20"
      OffenseID:
        simple: ${inputs.ID}
      OffenseStartTime:
        simple: ${inputs.StartTime}
      QID:
        complex:
          accessor: Correlation.QID}
          root: ${QRadar
          transformers:
          - operator: uniq
          - operator: Stringify
          - args:
              separator:
                value:
                  simple: ) ILIKE '%' OR RULENAME(
            operator: join
      additionalQueryFields:
        simple: ${QRadar.AdditionalFields}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook get the correlation logs of multiple QIDs.
      id: c70a8cd7-e6ac-4d7a-8aae-d322d9d3d248
      iscommand: false
      name: QRadarCorrelationLog
      playbookId: QRadarCorrelationLog
      type: playbook
      version: -1
    taskid: c70a8cd7-e6ac-4d7a-8aae-d322d9d3d248
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 520,
          "y": 1600
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: QRadar.AdditionalFields
      stringify: {}
      value:
        complex:
          root: inputs.Fields
          transformers:
          - args:
              limit: {}
              replaceWith:
                value:
                  simple: '","'
              toReplace:
                value:
                  simple: ','
            operator: replace
          - args:
              prefix:
                value:
                  simple: ',"'
              suffix:
                value:
                  simple: '"'
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value into the context with the given context key
      id: 3ea301ec-88ce-4a87-8205-55ab4af1153a
      iscommand: false
      name: Setup additional fields
      script: Set
      type: regular
      version: -1
    taskid: 3ea301ec-88ce-4a87-8205-55ab4af1153a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 295,
          "y": 720
        }
      }
  "24":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Fields
          operator: isNotEmpty
      label: "true"
    id: "24"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "11"
      - "12"
      "true":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: e610fb0b-a75f-4925-83ad-7fdbaa169d0a
      iscommand: false
      name: Are there additional fields
      type: condition
      version: -1
    taskid: e610fb0b-a75f-4925-83ad-7fdbaa169d0a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 295,
          "y": 515
        }
      }
  "25":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isEqualString
          right:
            value:
              simple: QRadar
      - - left:
            iscontext: true
            value:
              simple: modules.state
          operator: isEqualString
          right:
            value:
              simple: active
      label: "yes"
    id: "25"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: 0876b8fd-d1a3-4519-8310-e0e8973cf071
      iscommand: false
      name: Is Qradar v1 enabled?
      type: condition
      version: -1
    taskid: 0876b8fd-d1a3-4519-8310-e0e8973cf071
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -240,
          "y": -280
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isEqualString
          right:
            value:
              simple: QRadar_v2
      - - left:
            iscontext: true
            value:
              simple: modules.state
          operator: isEqualString
          right:
            value:
              simple: active
      label: "yes"
    id: "26"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: 3f254d5a-a5f6-4dc5-8f00-fc777a1e9efe
      iscommand: false
      name: Is Qradar v2 enabled?
      type: condition
      version: -1
    taskid: 3f254d5a-a5f6-4dc5-8f00-fc777a1e9efe
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -960,
          "y": -280
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: EpochTime
      stringify: {}
      value:
        complex:
          root: inputs.StartTime
          transformers:
          - args:
              formatter:
                value:
                  simple: '%Y-%m-%dT%H:%M:%S.%fZ'
            operator: FormattedDateToEpoch
    separatecontext: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: 3999e34f-ff50-40da-8d9a-8e9b9660d3ae
    type: regular
    task:
      id: 3999e34f-ff50-40da-8d9a-8e9b9660d3ae
      version: -1
      name: Set timestamp
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      append: {}
      key:
        simple: Time
      stringify: {}
      value:
        complex:
          root: inputs.StartTime
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -1070,
          "y": -30
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "6_2_#default#": 0.8
    },
    "paper": {
      "dimensions": {
        "height": 2315,
        "width": 2090,
        "x": -1070,
        "y": -440
      }
    }
  }

fromversion: 5.0.0
tests:
- test playbook - QRadarCorreltaions
