id: PhishTank Testing
version: -1
name: PhishTank Testing
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7aaefdb3-41b2-4c42-8cd1-54f706951e5f
    type: start
    task:
      id: 7aaefdb3-41b2-4c42-8cd1-54f706951e5f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: ea01decf-54f8-45f1-8a7d-3a3873e8dc29
    type: regular
    task:
      id: ea01decf-54f8-45f1-8a7d-3a3873e8dc29
      version: -1
      name: Check URL
      description: Check URL Reputation
      script: '|||url'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "3"
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${badURL}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 0a2da204-3f8f-4eab-83df-f878268723f5
    type: regular
    task:
      id: 0a2da204-3f8f-4eab-83df-f878268723f5
      version: -1
      name: Verify URL Data
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Data
      path:
        simple: URL
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 5cc2b958-d69e-43b2-89f6-55ceb23ef902
    type: regular
    task:
      id: 5cc2b958-d69e-43b2-89f6-55ceb23ef902
      version: -1
      name: Verify DBotScore
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Indicator,Score,Type,Vendor
      path:
        simple: DBotScore
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: ff7a088b-0315-4569-85e8-ec5556bd0b1f
    type: title
    task:
      id: ff7a088b-0315-4569-85e8-ec5556bd0b1f
      version: -1
      name: Success
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: be16d6b0-c31f-48c8-8802-a4d71351a0e9
    type: regular
    task:
      id: be16d6b0-c31f-48c8-8802-a4d71351a0e9
      version: -1
      name: Download phishtank CSV
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      body: {}
      filename:
        simple: phishtank.csv
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      url:
        simple: http://data.phishtank.com/data/online-valid.csv
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 2460c597-5995-4288-887d-60873622416e
    type: regular
    task:
      id: 2460c597-5995-4288-887d-60873622416e
      version: -1
      name: Load file to context
      scriptName: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize:
        simple: "2000"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: e8f9b718-59b5-431e-8e37-66b1025b321e
    type: regular
    task:
      id: e8f9b718-59b5-431e-8e37-66b1025b321e
      version: -1
      name: Set badURL
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      append: {}
      key:
        simple: badURL
      value:
        simple: ${FileData=val.split('\n')[1].split(',')[1]}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 60b545ed-5c7c-4bc2-8131-00da26d2b52c
    type: regular
    task:
      id: 60b545ed-5c7c-4bc2-8131-00da26d2b52c
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0