id: GraphQL - Test
version: -1
name: GraphQL - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d198fc66-bd7e-405f-87d4-bd438b2513b5
    type: start
    task:
      id: d198fc66-bd7e-405f-87d4-bd438b2513b5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 2df822d5-b0d0-418c-80d6-a71e60a894f9
    type: regular
    task:
      id: 2df822d5-b0d0-418c-80d6-a71e60a894f9
      version: -1
      name: GraphQL Query
      description: Execute a query request to the GraphQL server.
      script: '|||graphql-query'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      query:
        simple: |-
          {
            country(code: "BR") {
              name
              native
              capital
              emoji
              currency
              languages {
                code
                name
              }
            }
          }
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 2c2691f8-29e2-4dd5-8bc7-456d32382878
    type: condition
    task:
      id: 2c2691f8-29e2-4dd5-8bc7-456d32382878
      version: -1
      name: Verify Query Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: GraphQL.country.name
            iscontext: true
          right:
            value:
              simple: Brazil
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 4a72c5c1-1b3d-4b79-86d7-0235f8c4866c
    type: regular
    task:
      id: 4a72c5c1-1b3d-4b79-86d7-0235f8c4866c
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: ad04df58-1876-4dde-8672-910738b0e6a1
    type: title
    task:
      id: ad04df58-1876-4dde-8672-910738b0e6a1
      version: -1
      name: Success
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
